categories: [Metabolomics]
description: Filter W4M data by values or metadata
homepage_url: https://github.com/HegemanLab/w4mclassfilter_galaxy_wrapper
long_description: Filter Workflow4Metabolomics data by feature-metadata, sample-metadata, or values in the data-matrix.
name: w4mclassfilter
owner: eschen42
remote_repository_url: https://github.com/HegemanLab/w4mclassfilter_galaxy_wrapper/tree/master
include:
  - .shed.yml
  - LICENSE
  - README
  - test-data/expected_dataMatrix.tsv
  - test-data/expected_sampleMetadata.tsv
  - test-data/expected_variableMetadata.tsv
  - test-data/rangefilter_dataMatrix.tsv
  - test-data/rangefilter_sampleMetadata.tsv
  - test-data/rangefilter_variableMetadata.tsv
  - test-data/input_dataMatrix.tsv
  - test-data/input_nofilter_dataMatrix.tsv
  - test-data/input_sampleMetadata.tsv
  - test-data/input_variableMetadata.tsv
  - w4mclassfilter.xml
  - w4mclassfilter_wrapper.R
